# clnrm OTEL validation template (v0.6.0)
# This file uses Tera templating syntax

[meta]
name = "{{ vars.name | default(value="otel_validation") }}"
version = "0.6.0"
description = "Telemetry-only validation test"

[otel]
exporter = "{{ env(name="OTEL_EXPORTER") | default(value="stdout") }}"
{% if otel.endpoint %}
endpoint = "{{ otel.endpoint }}"
{% endif %}
sample_ratio = 1.0
resources = { "service.name" = "clnrm", "service.version" = "0.6.0" }

[service.clnrm]
plugin = "generic_container"
image = "{{ vars.image | default(value="alpine:latest") }}"
args = ["sh", "-c", "echo 'Running test'"]
wait_for_span = "clnrm.run"

[[scenario]]
name = "otel_validation"
service = "clnrm"
run = "echo 'Test execution'"

[[expect.span]]
name = "clnrm.run"
kind = "internal"
attrs.all = { "result" = "pass" }

[expect.counts]
spans_total = { gte = 1 }
errors_total = { eq = 0 }

{% if vars.deterministic %}
[determinism]
seed = 42
freeze_clock = "2025-01-01T00:00:00Z"
{% endif %}

[report]
json = "{{ vars.report_dir | default(value="reports") }}/report.json"
digest = "{{ vars.report_dir | default(value="reports") }}/digest.sha256"
