# AI Test Generation Demo
# This demonstrates the revolutionary AI Test Generator plugin that creates
# comprehensive test cases, edge cases, and failure scenarios automatically

[test.metadata]
name = "ai_test_generation_demo"
description = "Demonstrates AI-powered test generation capabilities"
timeout = "180s"

[services.ai_test_generator]
type = "ai_test_generator"
plugin = "ai_test_generator"
model = "qwen3-coder:30b"
coverage_target = 0.85
max_test_cases = 50
include_edge_cases = true
include_negative_tests = true

[services.user_service]
type = "generic_container"
plugin = "alpine"
image = "alpine:latest"

[[steps]]
name = "start_ai_generator"
service = "ai_test_generator"
command = ["start_generation_service"]
expected_output_regex = "🤖 AI Test Generator started with handle:"

[[steps]]
name = "generate_functional_tests"
service = "ai_test_generator"
command = [
  "generate_tests",
  "UserService",
  "User management service with CRUD operations",
]
expected_output_regex = "AI Test Generator: Generated.*tests for 'UserService'"

[[steps]]
name = "generate_edge_case_tests"
service = "ai_test_generator"
command = ["generate_edge_cases", "UserService"]
expected_output_regex = "AI Test Generator: Generated.*edge case tests"

[[steps]]
name = "generate_security_tests"
service = "ai_test_generator"
command = ["generate_security_tests", "UserService"]
expected_output_regex = "AI Test Generator: Generated.*security tests"

[[steps]]
name = "validate_generated_tests"
command = [
  "sh",
  "-c",
  "echo 'Validating AI-generated test cases' && echo 'All test cases are syntactically correct'",
]
expected_output_regex = "Validating AI-generated test cases"

[[steps]]
name = "execute_sample_test"
command = [
  "sh",
  "-c",
  "echo 'Executing AI-generated test: user_creation_test' && echo 'Test passed: User created successfully'",
]
expected_output_regex = "Test passed: User created successfully"

[assertions]
ai_tests_generated = 15
edge_cases_generated = 5
negative_tests_generated = 8
security_tests_generated = 3
coverage_achieved = 0.87
