# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clnrm < Formula
  desc "Hermetic integration testing platform with container isolation"
  homepage "https://github.com/seanchatmangpt/clnrm"
  url "https://github.com/seanchatmangpt/clnrm/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "f484bb74fe82bcf381cbbf706fdfe7cf989c9c37958e7c3b39ed64f888529b41"
  license "MIT"
  head "https://github.com/seanchatmangpt/clnrm.git", branch: "master"

  bottle do
    root_url "https://github.com/seanchatmangpt/clnrm/releases/download/v1.0.0"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
    sha256 cellar: :any_skip_relocation, ventura: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
    sha256 cellar: :any_skip_relocation, monterey: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
  end

  depends_on "rust" => :build

  def install
    # Build and install with OTEL features enabled
    system "cargo", "install", "--features", "otel", *std_cargo_args(path: "crates/clnrm-cli")

    # Install registry to share/clnrm/registry
    # The registry contains OpenTelemetry Weaver schemas that validate
    # the framework's telemetry output at runtime. This is critical for
    # the framework's false-positive detection capabilities.
    #
    # Installation layout:
    #   #{share}/clnrm/registry/registry_manifest.yaml  (registry metadata)
    #   #{share}/clnrm/registry/core/                   (core span schemas)
    #   #{share}/clnrm/registry/metrics/                (metric definitions)
    #   #{share}/clnrm/registry/events/                 (event definitions)
    #   #{share}/clnrm/registry/cli/                    (CLI operation schemas)
    (share/"clnrm/registry").mkpath
    (share/"clnrm/registry").install Dir["registry/*"]
  end

  def test
    # Test version output
    assert_match "clnrm", shell_output("#{bin}/clnrm --version")

    # Test help output
    assert_match "Hermetic integration testing platform", shell_output("#{bin}/clnrm --help")

    # Test that registry was installed correctly
    assert_predicate share/"clnrm/registry/registry_manifest.yaml", :exist?,
                     "Registry manifest not found - registry installation failed"
    assert_predicate share/"clnrm/registry/core", :directory?,
                     "Registry core schemas not found"
    assert_predicate share/"clnrm/registry/metrics", :directory?,
                     "Registry metrics not found"
    assert_predicate share/"clnrm/registry/events", :directory?,
                     "Registry events not found"

    # Test basic functionality - initialize a test project
    test_dir = testpath/"test-project"
    test_dir.mkpath

    system "#{bin}/clnrm", "init", "test-project"
    assert_predicate testpath/"test-project/cleanroom.toml", :exist?
    assert_predicate testpath/"test-project/tests", :directory?

    # Test validation command
    system "#{bin}/clnrm", "validate", testpath/"test-project/cleanroom.toml"

    # Test plugins command
    assert_match "Available plugins", shell_output("#{bin}/clnrm plugins")

    # Test that self-test can find the registry
    # This validates the fix for the registry path bug
    system "#{bin}/clnrm", "self-test", "--suite", "basic"
  end
end
