# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clnrm < Formula
  desc "Hermetic integration testing platform with container isolation"
  homepage "https://github.com/seanchatmangpt/clnrm"
  url "https://github.com/seanchatmangpt/clnrm/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "f484bb74fe82bcf381cbbf706fdfe7cf989c9c37958e7c3b39ed64f888529b41"
  license "MIT"
  head "https://github.com/seanchatmangpt/clnrm.git", branch: "master"

  bottle do
    root_url "https://github.com/seanchatmangpt/clnrm/releases/download/v1.0.0"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
    sha256 cellar: :any_skip_relocation, ventura: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
    sha256 cellar: :any_skip_relocation, monterey: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "PLACEHOLDER_UPDATE_AFTER_BOTTLE_BUILD"
  end

  depends_on "rust" => :build

  def install
    cd "crates/clnrm" do
      system "cargo", "install", *std_cargo_args
    end
  end

  def test
    assert_match "clnrm", shell_output("#{bin}/clnrm --version")
    assert_match "Hermetic integration testing platform", shell_output("#{bin}/clnrm --help")
  end
end
