/// Core Code Generation Engine

use crate::config::GeneratorConfig;
use crate::ontology::{Instances, Ontology, GeneratedArtifact, ArtifactType};
use crate::error::Result;
use std::path::PathBuf;
use tera::Tera;
use chrono::Utc;

/// Main code generator
pub struct CodeGenerator {
    config: GeneratorConfig,
    tera: Tera,
}

impl CodeGenerator {
    pub fn new(config: GeneratorConfig) -> Result<Self> {
        let mut tera = Tera::default();

        // Load templates from disk
        if config.generation.templates_dir.exists() {
            let pattern = format!(
                "{}/**/*.tera",
                config.generation.templates_dir.display()
            );
            tera.add_raw_templates(vec![])
                .map_err(|e| crate::error::GgenError::TemplateError(e))?;
        }

        Ok(Self { config, tera })
    }

    /// Generate all artifacts from ontology and instances
    pub async fn generate(&self) -> Result<()> {
        tracing::info!("Starting code generation");

        // Load ontology
        let ontology_paths = self.config.get_ontology_paths();
        if ontology_paths.is_empty() {
            return Err("No ontology files found".into());
        }

        // Load instances
        let instance_path = ontology_paths[0].join("clnrm-instances.ttl");
        let instances = Instances::from_file(&instance_path).await?;

        tracing::info!("Loaded {} instances", instances.instances.len());

        // Generate artifacts
        let mut artifacts = Vec::new();

        // 1. Generate Rust types
        artifacts.extend(self.generate_rust_types(&instances).await?);

        // 2. Generate trait implementations
        artifacts.extend(self.generate_trait_impls(&instances).await?);

        // 3. Generate test configuration
        artifacts.extend(self.generate_test_config(&instances).await?);

        // 4. Generate documentation
        artifacts.extend(self.generate_documentation(&instances).await?);

        // Write all artifacts
        for artifact in artifacts {
            artifact.write().await?;
            tracing::info!("Generated: {}", artifact.path.display());
        }

        tracing::info!("✅ Code generation complete");
        Ok(())
    }

    /// Generate Rust type definitions from instances
    async fn generate_rust_types(&self, instances: &Instances) -> Result<Vec<GeneratedArtifact>> {
        let mut artifacts = Vec::new();

        // Group instances by type
        let mut by_type: std::collections::HashMap<String, Vec<_>> = std::collections::HashMap::new();
        for instance in instances.instances.values() {
            by_type
                .entry(instance.class_type.clone())
                .or_insert_with(Vec::new)
                .push(instance);
        }

        // Generate types for each class
        for (class_name, class_instances) in by_type {
            let content = self.generate_type_for_class(&class_name, &class_instances)?;

            let artifact = GeneratedArtifact::new(
                format!("{}_types", class_name.to_lowercase()),
                ArtifactType::RustCode,
                content,
                self.config.generation.output_dir.join(format!(
                    "{}_types.rs",
                    class_name.to_lowercase()
                )),
            );

            artifacts.push(artifact);
        }

        Ok(artifacts)
    }

    /// Generate trait implementations for services
    async fn generate_trait_impls(&self, instances: &Instances) -> Result<Vec<GeneratedArtifact>> {
        // Get all service instances
        let services = instances.get_instances_of_type("Service");

        if services.is_empty() {
            return Ok(Vec::new());
        }

        let mut code = String::from(
            "// Generated by ggen\n\
             // Service Plugin trait implementations\n\n\
             use async_trait::async_trait;\n\
             use std::result::Result as StdResult;\n\n"
        );

        for service in services {
            if let Some(name) = &service.label {
                let service_name = name
                    .replace(" ", "")
                    .replace("-", "_");

                if let Some(service_type) = service.properties.get("serviceType") {
                    let type_str = service_type.as_string().unwrap_or("Generic");

                    code.push_str(&format!(
                        "/// {}\n\
                         #[derive(Debug, Clone)]\n\
                         pub struct {} {{\n    \
                         pub name: String,\n    \
                         pub service_type: String,\n\
                         }}\n\n\
                         impl {} {{\n    \
                         pub fn new() -> Self {{\n        \
                         Self {{\n            \
                         name: \"{}\".to_string(),\n            \
                         service_type: \"{}\".to_string(),\n        \
                         }}\n    \
                         }}\n\
                         }}\n\n",
                        name,
                        service_name,
                        service_name,
                        name,
                        type_str
                    ));
                }
            }
        }

        let artifact = GeneratedArtifact::new(
            "service_impls".to_string(),
            ArtifactType::RustCode,
            code,
            self.config.generation.output_dir.join("service_impls.rs"),
        );

        Ok(vec![artifact])
    }

    /// Generate test configuration from instances
    async fn generate_test_config(&self, instances: &Instances) -> Result<Vec<GeneratedArtifact>> {
        let test_configs = instances.get_instances_of_type("TestConfiguration");

        let mut artifacts = Vec::new();

        for config in test_configs {
            if let Some(name) = &config.label {
                let mut toml_content = String::from(
                    "# Generated by ggen\n\
                     # Test Configuration\n\n\
                     [metadata]\n"
                );

                if let Some(test_name) = config.properties.get("testName") {
                    if let Some(name_str) = test_name.as_string() {
                        toml_content.push_str(&format!("name = \"{}\"\n", name_str));
                    }
                }

                if let Some(description) = config.properties.get("testDescription") {
                    if let Some(desc_str) = description.as_string() {
                        toml_content.push_str(&format!("description = \"{}\"\n", desc_str));
                    }
                }

                toml_content.push_str("\n[scenario]\nname = \"main\"\n");

                let filename = name
                    .to_lowercase()
                    .replace(" ", "-")
                    .replace("test", "");

                let artifact = GeneratedArtifact::new(
                    format!("{}_config", filename),
                    ArtifactType::TomlConfig,
                    toml_content,
                    self.config.generation.output_dir.join(format!(
                        "{}-test.toml",
                        filename
                    )),
                );

                artifacts.push(artifact);
            }
        }

        Ok(artifacts)
    }

    /// Generate documentation from instances
    async fn generate_documentation(&self, instances: &Instances) -> Result<Vec<GeneratedArtifact>> {
        let mut artifacts = Vec::new();

        // Generate service registry documentation
        let services = instances.get_instances_of_type("Service");
        if !services.is_empty() {
            let mut doc = String::from(
                "# Generated Service Registry\n\n\
                 Auto-generated from RDF instances.\n\n"
            );

            doc.push_str("## Available Services\n\n");

            for service in services {
                if let Some(name) = &service.label {
                    doc.push_str(&format!("### {}\n\n", name));

                    if let Some(comment) = &service.comment {
                        doc.push_str(&format!("{}\n\n", comment));
                    }

                    if let Some(image) = service.properties.get("containerImage") {
                        if let Some(img_str) = image.as_string() {
                            doc.push_str(&format!("**Image**: `{}`\n\n", img_str));
                        }
                    }

                    if let Some(port) = service.properties.get("exposedPort") {
                        if let Some(port_num) = port.as_integer() {
                            doc.push_str(&format!("**Port**: {}\n\n", port_num));
                        }
                    }
                }
            }

            let artifact = GeneratedArtifact::new(
                "services_doc".to_string(),
                ArtifactType::Markdown,
                doc,
                self.config.generation.output_dir.join("SERVICES.md"),
            );

            artifacts.push(artifact);
        }

        Ok(artifacts)
    }

    /// Helper: Generate Rust type for a class
    fn generate_type_for_class(
        &self,
        class_name: &str,
        instances: &[&crate::ontology::Instance],
    ) -> Result<String> {
        let mut code = String::new();

        code.push_str(&format!(
            "// Generated type: {}\n\
             #[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n\
             pub struct {} {{\n",
            class_name, class_name
        ));

        // Extract common properties from instances
        if let Some(first) = instances.first() {
            for (prop_name, prop_value) in &first.properties {
                let rust_type = match prop_value {
                    crate::ontology::InstanceProperty::String(_) => "String".to_string(),
                    crate::ontology::InstanceProperty::Integer(_) => "i64".to_string(),
                    crate::ontology::InstanceProperty::Boolean(_) => "bool".to_string(),
                    crate::ontology::InstanceProperty::Decimal(_) => "f64".to_string(),
                    crate::ontology::InstanceProperty::Reference(_) => "String".to_string(),
                    crate::ontology::InstanceProperty::List(_) => "Vec<String>".to_string(),
                };

                let field_name = prop_name
                    .to_lowercase()
                    .replace("-", "_");

                code.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
            }
        }

        code.push_str("}\n\n");

        // Add Default implementation
        code.push_str(&format!(
            "impl Default for {} {{\n\
             fn default() -> Self {{\n\
             Self {{\n",
            class_name
        ));

        if let Some(first) = instances.first() {
            for prop_name in first.properties.keys() {
                let field_name = prop_name
                    .to_lowercase()
                    .replace("-", "_");
                code.push_str(&format!("    {}: Default::default(),\n", field_name));
            }
        }

        code.push_str("            }\n        }\n    }\n");

        Ok(code)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let config = GeneratorConfig::default();
        let _generator = CodeGenerator::new(config).expect("Failed to create generator");
    }

    #[tokio::test]
    async fn test_generate_trait_impls() {
        let config = GeneratorConfig::default();
        let generator = CodeGenerator::new(config).expect("Failed to create generator");
        let instances = Instances::new("test".to_string());

        let artifacts = generator
            .generate_trait_impls(&instances)
            .await
            .expect("Failed to generate");

        assert!(!artifacts.is_empty());
    }
}
