# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Clnrm < Formula
  desc "Hermetic integration testing platform with container isolation"
  homepage "https://github.com/seanchatmangpt/clnrm"
  url "https://github.com/seanchatmangpt/clnrm/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "0677ed1c820997188b4012471e2d5ddbcbc9b86c63e752cdda6863b8f6f53a3d"
  license "MIT"
  head "https://github.com/seanchatmangpt/clnrm.git", branch: "master"

  bottle do
    root_url "https://github.com/seanchatmangpt/clnrm/releases/download/v0.4.0"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "b1c2d3e4f5a6789012345678901234567890abcdef1234567890abcdef123456"
    sha256 cellar: :any_skip_relocation, ventura: "c2d3e4f5a6b7890123456789012345678901234567890abcdef1234567890abcdef"
    sha256 cellar: :any_skip_relocation, monterey: "d3e4f5a6b7c8901234567890123456789012345678901234567890abcdef123456"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "e4f5a6b7c8d9012345678901234567890123456789012345678901234567890abcdef"
  end

  depends_on "rust" => :build

  def install
    # Build with OTEL features enabled
    system "cargo", "build", "--release", "--features", "otel"
    bin.install "target/release/clnrm"

    # Install registry to share/clnrm/registry
    # The registry contains OpenTelemetry Weaver schemas that validate
    # the framework's telemetry output at runtime. This is critical for
    # the framework's false-positive detection capabilities.
    #
    # Installation layout:
    #   #{share}/clnrm/registry/registry_manifest.yaml  (registry metadata)
    #   #{share}/clnrm/registry/core/                   (core span schemas)
    #   #{share}/clnrm/registry/metrics/                (metric definitions)
    #   #{share}/clnrm/registry/events/                 (event definitions)
    #   #{share}/clnrm/registry/cli/                    (CLI operation schemas)
    (share/"clnrm/registry").mkpath
    (share/"clnrm/registry").install Dir["registry/*"]
  end

  def test
    # Test version output
    assert_match "clnrm", shell_output("#{bin}/clnrm --version")

    # Test help output
    assert_match "Hermetic integration testing platform", shell_output("#{bin}/clnrm --help")

    # Test that registry was installed correctly
    assert_predicate share/"clnrm/registry/registry_manifest.yaml", :exist?,
                     "Registry manifest not found - registry installation failed"
    assert_predicate share/"clnrm/registry/core", :directory?,
                     "Registry core schemas not found"
    assert_predicate share/"clnrm/registry/metrics", :directory?,
                     "Registry metrics not found"
    assert_predicate share/"clnrm/registry/events", :directory?,
                     "Registry events not found"

    # Test basic functionality - initialize a test project
    test_dir = testpath/"test-project"
    test_dir.mkpath

    system "#{bin}/clnrm", "init", "test-project"
    assert_predicate testpath/"test-project/cleanroom.toml", :exist?
    assert_predicate testpath/"test-project/tests", :directory?

    # Test validation command
    system "#{bin}/clnrm", "validate", testpath/"test-project/cleanroom.toml"

    # Test plugins command
    assert_match "Available plugins", shell_output("#{bin}/clnrm plugins")

    # Test that self-test can find the registry
    # This validates the fix for the registry path bug
    system "#{bin}/clnrm", "self-test", "--suite", "basic"
  end
end
