use serde::{Deserialize, Serialize};

/// Verdict of the truex execution.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum Verdict {
    /// The procedure passed successfully.
    Passed,
    /// The procedure failed.
    Failed,
    /// The procedure was skipped.
    Skipped,
}

/// TruexReceipt is the definitive struct per the PRD.
/// It contains cryptographic hashes and metadata to ensure the integrity
/// and non-repudiation of pipeline executions.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TruexReceipt {
    /// Hash of the input to the procedure.
    pub input_hash: String,
    
    /// Hash of the output generated by the procedure.
    pub output_hash: String,
    
    /// Hash of the closure (environment and dependencies).
    pub closure_hash: String,
    
    /// Hash of the executed procedure (code/binary).
    pub procedure_hash: String,
    
    /// Post-Quantum Cryptography seal for future-proofing signatures.
    pub pqc_seal: String,
    
    /// Hash of the previous receipt to form a verifiable chain.
    pub previous_receipt_hash: String,
    
    /// Identity of the actor performing the execution.
    pub actor_id: String,
    
    /// Transport mechanism or protocol used.
    pub transport: String,
    
    /// Unique identifier for the execution session.
    pub session_id: String,
    
    /// Pointer for replayability of the execution.
    pub replay_pointer: String,
    
    /// The final verdict of the execution.
    pub verdict: Verdict,
}

impl TruexReceipt {
    /// Creates a new `TruexReceipt`.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        input_hash: String,
        output_hash: String,
        closure_hash: String,
        procedure_hash: String,
        pqc_seal: String,
        previous_receipt_hash: String,
        actor_id: String,
        transport: String,
        session_id: String,
        replay_pointer: String,
        verdict: Verdict,
    ) -> Self {
        Self {
            input_hash,
            output_hash,
            closure_hash,
            procedure_hash,
            pqc_seal,
            previous_receipt_hash,
            actor_id,
            transport,
            session_id,
            replay_pointer,
            verdict,
        }
    }
}
