#!/bin/bash
# Setup script to create clnrm-cli directory with ggen.toml

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLI_DIR="$PROJECT_ROOT/clnrm-cli"

echo "🚀 Setting up clnrm-cli directory..."

# Create clnrm-cli directory
mkdir -p "$CLI_DIR"

# Copy ggen.toml template
cp "$SCRIPT_DIR/ggen.toml.tmpl" "$CLI_DIR/ggen.toml"

# Create .gitignore
cat > "$CLI_DIR/.gitignore" << 'EOF'
# Generated source files
src/

# Build artifacts
target/
Cargo.lock

# IDE files
.idea/
.vscode/
*.swp
*.swo
*~
EOF

# Create initial README
cat > "$CLI_DIR/README.md" << 'EOF'
# clnrm-cli

Pure CLI crate generated by `ggen` from RDF definitions.

## Setup

1. Edit `ggen.toml` to configure generation
2. Run: `ggen project gen`
3. Build: `cargo build`

## Editing Configuration

Edit `ggen.toml` to:
- Change RDF source files
- Modify template path
- Update output directory
- Configure generation options

## Regenerating

After editing `ggen.toml`:
```bash
ggen project gen
```

This will regenerate all source files from the template and RDF definitions.
EOF

echo "✅ Created clnrm-cli directory at: $CLI_DIR"
echo ""
echo "Next steps:"
echo "  1. cd clnrm-cli"
echo "  2. Edit ggen.toml (if needed)"
echo "  3. ggen project gen"
echo "  4. cargo build"

