[package]
name = "clnrm-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Cleanroom Testing Framework - Core library"

[lib]
name = "clnrm_core"
path = "src/lib.rs"

[dependencies]
# Core dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

# Container dependencies
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
futures-util = { workspace = true }
surrealdb = { workspace = true }

# CLI dependencies
clap = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
toml = { workspace = true }
regex = { workspace = true }
walkdir = { workspace = true }
tempfile = { workspace = true }
junit-report = { workspace = true }
notify = { workspace = true }

# OpenTelemetry dependencies
opentelemetry = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
opentelemetry-stdout = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, optional = true }
tracing-opentelemetry = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

# Utility dependencies
uuid = { workspace = true }
chrono = { workspace = true }

[features]
default = []
otel-stdout = ["opentelemetry-stdout"]
otel-logs = ["opentelemetry", "opentelemetry_sdk"]
otel-traces = [
  "opentelemetry",
  "opentelemetry_sdk",
  "opentelemetry-stdout",
  "opentelemetry-otlp",
  "tracing-opentelemetry",
  "tracing-subscriber",
]
otel-metrics = ["opentelemetry", "opentelemetry_sdk"]
otel = ["otel-traces", "otel-metrics", "otel-stdout", "otel-logs"]
