//! Test Receipt Infrastructure (Γₜ)
//!
//! Cryptographically verifiable receipts for test executions.
//!
//! ## Overview
//!
//! Every test execution in the cleanroom framework emits a **test receipt** (Γₜ),
//! a cryptographically verifiable proof that documents:
//!
//! - **What was tested**: Scenario ID, capabilities exercised, effects produced
//! - **How it was tested**: Environment ontology (Σ*), constraints, image digests
//! - **That validation passed**: Weaver proof, timing validation, hermeticity witness
//! - **When it was tested**: Timestamp, hash chain linking
//!
//! ## Features
//!
//! ### Content-Addressable Storage
//!
//! Receipts are indexed by their SHA-256 hash, ensuring immutability and
//! enabling deduplication of identical test executions.
//!
//! ### Hash Chain Linking
//!
//! Receipts form a tamper-evident chain where each receipt references the
//! previous receipt's hash. This creates an immutable audit trail of all
//! test executions.
//!
//! ### Cryptographic Signing (Optional)
//!
//! Receipts can be signed with Ed25519 signatures for non-repudiation and
//! authenticity verification. Enable with the `crypto` feature.
//!
//! ### Weaver Validation Proof
//!
//! Receipts include proof that OpenTelemetry Weaver schema validation passed,
//! documenting the exact telemetry emitted and validated.
//!
//! ### Timing Footprint
//!
//! Receipts capture hot/warm/cold path timings and τ violations, enabling
//! performance regression detection across test runs.
//!
//! ### Hermeticity Witness
//!
//! Receipts prove that tests ran in isolation with no external connections,
//! no non-hermetic file access, and deterministic execution.
//!
//! ## Example Usage
//!
//! ```rust,no_run
//! use clnrm_core::receipts::{ReceiptStore, TestReceipt};
//! use clnrm_core::environment::sigma::ContentHash;
//!
//! # fn example() -> clnrm_core::error::Result<()> {
//! // Create receipt store
//! let store = ReceiptStore::new();
//!
//! // Store a receipt (generated by EnvironmentCompiler)
//! # let receipt = TestReceipt::default();
//! let receipt_id = store.put(receipt)?;
//!
//! // Retrieve receipt
//! let retrieved = store.get(&receipt_id)?;
//!
//! // Validate hash chain
//! let validation = store.validate_chain()?;
//! assert!(validation.valid);
//!
//! // Get recent receipts
//! let recent = store.get_chain(Some(10))?;
//! # Ok(())
//! # }
//! ```
//!
//! ## Integration with Environment Compiler
//!
//! The `EnvironmentCompiler` automatically generates receipts during compilation:
//!
//! ```rust,no_run
//! use clnrm_core::environment::compiler::EnvironmentCompiler;
//! use clnrm_core::environment::store::OntologyStore;
//! use clnrm_core::receipts::ReceiptStore;
//! use std::sync::Arc;
//!
//! # fn example() -> clnrm_core::error::Result<()> {
//! let ontology_store = Arc::new(OntologyStore::new());
//! let receipt_store = Arc::new(ReceiptStore::new());
//!
//! let compiler = EnvironmentCompiler::new(ontology_store.clone());
//!
//! // Compile environment (automatically generates receipt)
//! # use clnrm_core::environment::sigma::ContentHash;
//! # use clnrm_core::capabilities::ConstraintSet;
//! # let base_hash = ContentHash::from_string("test");
//! # let constraints = ConstraintSet::default();
//! let compiled = compiler.compile(&base_hash, None, &constraints)?;
//!
//! // Receipt is available in compiled.proof_metadata
//! let receipt = compiled.proof_metadata.receipt;
//! receipt_store.put(receipt)?;
//! # Ok(())
//! # }
//! ```

pub mod receipt;
pub mod store;

// Re-export commonly used types
pub use receipt::{
    HermeticityWitness, ImageDigest, OtelGraphProof, PathTiming, ReceiptId, ReceiptSignature,
    TestReceipt, TimingFootprint, TimingViolation, WeaverProof,
};
pub use store::{ChainValidationResult, ReceiptStore};
