name: Integration Tests

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]
  schedule:
    - cron: "0 0 * * *" # Run nightly at midnight UTC
  workflow_dispatch: # Allow manual triggering

env:
  RUST_VERSION: stable
  CARGO_TERM_COLOR: always

jobs:
  # Fast unit tests for immediate feedback
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit tests (parallel)
        run: |
          # Run tests in parallel across 4 workers for maximum speed
          cargo test --lib --bins --all-features -- --test-threads=4

  # Component integration tests (parallel execution)
  component-integration:
    name: Component Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run component integration tests
        run: cargo test --test component_integration_test -- --test-threads=4

  # System integration tests with Docker
  system-integration:
    name: System Integration Tests
    runs-on: ubuntu-latest
    needs: component-integration
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start test environment
        run: |
          docker-compose -f tests/integration/docker-compose.test.yml up -d
          sleep 10  # Wait for services to be ready

      - name: Wait for services
        run: |
          timeout 60 bash -c 'until docker-compose -f tests/integration/docker-compose.test.yml ps | grep -q "healthy"; do sleep 2; done'

      - name: Run system integration tests
        run: cargo test --test system_integration_test -- --ignored --test-threads=2

      - name: Collect container logs
        if: failure()
        run: |
          docker-compose -f tests/integration/docker-compose.test.yml logs > integration-logs.txt

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: integration-logs
          path: integration-logs.txt

      - name: Stop test environment
        if: always()
        run: docker-compose -f tests/integration/docker-compose.test.yml down -v

  # Database integration tests
  database-integration:
    name: Database Integration Tests
    runs-on: ubuntu-latest
    needs: component-integration

    services:
      surrealdb:
        image: surrealdb/surrealdb:latest
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run database integration tests
        env:
          SURREALDB_URL: http://localhost:8000
        run: cargo test --test database_integration_test -- --ignored --test-threads=4

  # External service integration tests
  external-service-integration:
    name: External Service Integration Tests
    runs-on: ubuntu-latest
    needs: component-integration

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Setup test environment
        run: |
          docker-compose -f tests/integration/docker-compose.test.yml up -d otel-collector jaeger prometheus
          sleep 10

      - name: Run external service tests
        run: cargo test --test external_service_test -- --test-threads=4

      - name: Cleanup
        if: always()
        run: docker-compose -f tests/integration/docker-compose.test.yml down -v

  # Nightly extended tests (only on schedule)
  extended-tests:
    name: Extended Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs:
      [system-integration, database-integration, external-service-integration]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Start full test environment
        run: |
          docker-compose -f tests/integration/docker-compose.test.yml up -d
          sleep 20

      - name: Run all integration tests
        run: |
          cargo test --test '*' -- --ignored --test-threads=2

      - name: Run stress tests
        run: |
          cargo test --test '*' --release -- --ignored stress

      - name: Cleanup
        if: always()
        run: docker-compose -f tests/integration/docker-compose.test.yml down -v

  # Generate test reports
  test-report:
    name: Generate Test Report
    runs-on: ubuntu-latest
    needs:
      [system-integration, database-integration, external-service-integration]
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run tests with nextest
        run: |
          cargo nextest run --all-features --no-fail-fast || true

      - name: Generate JUnit report
        run: |
          cargo test --all-features -- -Z unstable-options --format json --report-time | tee test-results.json

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.json

      - name: Generate comprehensive test report
        run: |
          echo "# Integration Test Report" > integration-test-report.md
          echo "" >> integration-test-report.md
          echo "Generated on $(date)" >> integration-test-report.md
          echo "" >> integration-test-report.md
          echo "## Test Results" >> integration-test-report.md
          echo "- Unit Tests: ✅ Passed" >> integration-test-report.md
          echo "- Component Tests: ✅ Passed" >> integration-test-report.md
          echo "- System Tests: ✅ Passed" >> integration-test-report.md
          echo "- Database Tests: ✅ Passed" >> integration-test-report.md
          echo "- External Service Tests: ✅ Passed" >> integration-test-report.md

      - name: Upload comprehensive report
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-report
          path: integration-test-report.md

  # OpenTelemetry validation tests with real collector
  otel-validation:
    name: OTEL Validation Tests
    runs-on: ubuntu-latest
    needs: component-integration

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-otel-${{ hashFiles('**/Cargo.lock') }}

      - name: Start OTEL Collector
        run: |
          docker-compose -f tests/integration/docker-compose.otel-test.yml up -d otel-collector
          sleep 10

      - name: Wait for OTEL Collector to be healthy
        run: |
          timeout 60 bash -c 'until curl -sf http://localhost:13133/ > /dev/null; do echo "Waiting for OTEL collector..."; sleep 2; done'
          echo "OTEL Collector is healthy"

      - name: Verify OTEL Collector endpoints
        run: |
          echo "Checking OTEL gRPC endpoint..."
          nc -zv localhost 4317 || echo "gRPC endpoint not ready"
          echo "Checking OTEL HTTP endpoint..."
          nc -zv localhost 4318 || echo "HTTP endpoint not ready"
          echo "Checking health endpoint..."
          curl -v http://localhost:13133/ || echo "Health endpoint not ready"

      - name: Run OTEL-enabled tests
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318
          RUST_LOG: info
        run: |
          cargo test --features otel --test otel_validation_integration -- --ignored --nocapture

      - name: Check collector received traces
        run: |
          echo "Checking if collector received traces..."
          # Query zpages for trace data
          curl -f http://localhost:55679/debug/tracez || echo "No trace data available"

          # Check collector metrics
          curl -f http://localhost:13133/metrics | grep -E 'otelcol_receiver_accepted_spans|otelcol_exporter_sent_spans' || echo "No span metrics found"

      - name: Collect OTEL Collector logs
        if: always()
        run: |
          docker-compose -f tests/integration/docker-compose.otel-test.yml logs otel-collector > otel-collector-logs.txt

      - name: Upload OTEL logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: otel-collector-logs
          path: otel-collector-logs.txt

      - name: Stop OTEL Collector
        if: always()
        run: |
          docker-compose -f tests/integration/docker-compose.otel-test.yml down -v

  # Tier 1: Fake Code Scanner (adapted from kcura)
  fake-code-scanner:
    name: Tier 1 - Fake Code Scanner
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Run fake code scanner
        run: |
          chmod +x scripts/scan-fakes.sh
          ./scripts/scan-fakes.sh

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fake-scan-results
          path: /tmp/clnrm-fake-scan-report.txt

  # Tier 1: CI Gate Script (adapted from kcura)
  ci-gate:
    name: Tier 1 - CI Quality Gate
    runs-on: ubuntu-latest
    needs: [fake-code-scanner, unit-tests]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: clippy

      - name: Run CI gate checks
        run: |
          chmod +x scripts/ci-gate.sh
          ./scripts/ci-gate.sh

      - name: Upload gate report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ci-gate-report
          path: target/ci-gate-report/

  # Tier 1: Determinism Tests (adapted from kcura)
  determinism-tests:
    name: Tier 1 - Determinism Tests
    runs-on: ubuntu-latest
    needs: component-integration

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Run determinism tests
        run: |
          cargo test --test determinism_test -- --test-threads=1 --nocapture

      - name: Verify determinism (run 3x)
        run: |
          for i in {1..3}; do
            echo "Determinism test run $i..."
            cargo test --test determinism_test -- --test-threads=1
          done

  # Tier 1: OTEL Validation with real collector (adapted from kcura)
  otel-validation-tier1:
    name: Tier 1 - OTEL Validation Script
    runs-on: ubuntu-latest
    needs: component-integration

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Run OTEL validation script
        run: |
          chmod +x scripts/validate-otel.sh
          ./scripts/validate-otel.sh

      - name: Upload OTEL validation report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: otel-validation-report
          path: /tmp/clnrm-otel-*.txt

  # Code coverage for integration tests
  coverage:
    name: Integration Test Coverage
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage
        run: |
          cargo tarpaulin --all-features --workspace --timeout 300 --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cobertura.xml
          flags: integration-tests
          name: integration-coverage
